# Generated by Django 5.2.1 on 2025-05-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_flight_duration_flight_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='seats_available',
            field=models.IntegerField(default=100),
        ),
    ]
